name: Eye Tracking Plotting Pipeline

on:
  push:
    paths:
      - 'data/**'  # Trigger on changes to files in the 'data' directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your required Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Make sure to have a requirements.txt file with your dependencies

    - name: Run plotting script
      run: |
        python plot_script.py  # Replace with your actual plotting script filename
